name: build-image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Login to DockerHub'
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: 'Login to Github Packages'
        uses: docker/login-action@v1
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Set latest tag'
        if: github.ref_name == 'master' || github.ref_name == 'main'
        run: echo "TAG=latest" >>${GITHUB_ENV}

      - name: 'Set tag name'
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG=${GITHUB_REF#refs/*/}" >>${GITHUB_ENV}

      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            schliflo/action-cloud-run:${{ env.TAG }}
            ghcr.io/schliflo/action-cloud-run:${{ env.TAG }}
